import type { Metadata } from "next";
import { AssistantChat } from "@/components/assistant/AssistantChat";
import { assistantConfigured, assistantProviderLabels } from "@/lib/llm";
import { requireUser } from "@/lib/session";
import { assistantDailyLimit, assistantRequestsToday } from "@/lib/usage";

export const metadata: Metadata = { title: "Study assistant" };

export default async function StudyPage() {
  const user = await requireUser();
  const used = await assistantRequestsToday(user.id);
  const limit = assistantDailyLimit(user.role);
  const providers = assistantProviderLabels();

  return (
    <>
      <h1 className="mb-1 font-serif text-3xl font-semibold">Study assistant</h1>
      <p className="mb-4 text-sm text-muted">Finds scriptures on any topic by searching the standard works.</p>

      <section aria-label="Disclaimer" className="mb-6 rounded-xl border border-line bg-card p-4 text-sm">
        <p className="font-medium">Please read before using the assistant</p>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-muted">
          <li>
            Answers are generated by AI and can be wrong, incomplete, or out of context. Every scripture it cites is
            checked against the real text, but read the verses yourself before relying on an explanation.
          </li>
          <li>It's a study aid, not an official source of doctrine, and it doesn't speak for the Church.</li>
          <li>It finds scriptures only. It won't write or outline talks or lessons; those are yours to prepare.</li>
          <li>
            What you type is sent to outside AI services
            {providers.length > 0 ? ` (${providers.join(", ")})` : ""} to produce the answer. Don't include private or
            sensitive information.
          </li>
          {providers.includes("Google Gemini") && (
            <li>
              Google's free Gemini service may use what you type to improve its products, and people at Google may
              review it.
            </li>
          )}
        </ul>
        <p className="mt-3 text-xs text-muted">
          {used}/{limit} of your requests used today.
        </p>
      </section>

      {assistantConfigured() ? (
        <AssistantChat />
      ) : (
        <div className="rounded-xl border border-dashed border-line p-6 text-sm text-muted">
          The assistant isn't set up yet. Add an AI provider key (<code>GEMINI_API_KEY</code>, <code>GROQ_API_KEY</code>,
          or <code>OPENROUTER_API_KEY</code>) to <code>.env.local</code> and restart the dev server.
        </div>
      )}
    </>
  );
}
