import type { Metadata } from "next";
import Link from "next/link";
import { AssistantChat } from "@/components/assistant/AssistantChat";
import { DeepStudyNotice } from "@/components/DeepStudyNotice";
import { assistantConfigured, assistantProviderLabels } from "@/lib/llm";
import { requireUser } from "@/lib/session";
import { assistantDailyLimit, assistantRequestsToday } from "@/lib/usage";

export const metadata: Metadata = { title: "Deep Study assistant" };

export default async function DeepStudyChatPage() {
  const user = await requireUser();
  const used = await assistantRequestsToday(user.id);
  const limit = assistantDailyLimit(user.role);
  const providers = assistantProviderLabels();

  return (
    <>
      <nav className="mb-2 text-sm text-muted">
        <Link href="/deep-study" className="hover:text-accent">Deep Study</Link>
      </nav>
      <h1 className="mb-1 font-serif text-3xl font-semibold">Deep Study assistant</h1>
      <p className="mb-4 text-sm text-muted">
        Finds an event or person in the scriptures and in other ancient writings, and sets the accounts side by side.
      </p>
      <DeepStudyNotice />

      <section aria-label="Disclaimer" className="mb-6 rounded-xl border border-line bg-card p-4 text-sm">
        <p className="font-medium">Please read before using the assistant</p>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-muted">
          <li>
            Answers are generated by AI and can be wrong or out of context. Every passage it cites is checked against the
            real text, but read the passages yourself.
          </li>
          <li>
            Passages from Josephus and other Deep Study texts are marked <em>Not scripture</em>. The assistant compares
            accounts; it doesn&apos;t decide which is right, and it doesn&apos;t speak for the Church.
          </li>
          <li>It won&apos;t write or outline talks or lessons.</li>
          <li>
            What you type is sent to outside AI services
            {providers.length > 0 ? ` (${providers.join(", ")})` : ""}. Don&apos;t include private or sensitive information.
          </li>
          {providers.includes("Google Gemini") && (
            <li>
              Google&apos;s free Gemini service may use what you type to improve its products, and people at Google may
              review it.
            </li>
          )}
        </ul>
        <p className="mt-3 text-xs text-muted">
          {used}/{limit} of your requests used today (shared with the study assistant).
        </p>
      </section>

      {assistantConfigured() ? (
        <AssistantChat userId={user.id} variant="deep-study" />
      ) : (
        <div className="rounded-xl border border-dashed border-line p-6 text-sm text-muted">
          The assistant isn&apos;t set up yet: no AI provider key is configured.
        </div>
      )}
    </>
  );
}
